In [48]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

In [49]:
thedata = pd.read_csv('diabetes.csv')
thedata.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Type,DKAprone,Hypertension
0,6,148,72,35,0,33.6,0.627,50,1,0,0,0
1,1,85,66,29,0,26.6,0.351,31,0,0,0,0
2,8,183,64,0,0,23.3,0.672,32,1,0,0,0
3,1,89,66,23,94,28.1,0.167,21,0,0,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0,0

In [51]:
thedata.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Type,DKAprone,Hypertension
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.0,768.0,768.0
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958,0.0,0.0,0.0
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951,0.0,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000,0.0,0.0,0.0
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000,0.0,0.0,0.0
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000,0.0,0.0,0.0
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000,0.0,0.0,0.0
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000,0.0,0.0,0.0

In [52]:
def calculate_new_value(row):
    if (row['Outcome']) == '1':
        if((int(row['Insulin'])<25) and (int(row['Pregnancies'])<6)):
            return 1
        else:
            return 2

    else:
        return 0

thedata['Type']= thedata.apply(calculate_new_value,axis=1)
thedata.to_csv('diabetes.csv', index= False)

In [53]:
tehdata

NameError: name 'tehdata' is not defined

In [54]:
def calculate_dkaprone(row):
    if (row['Outcome']) == '1':
        if((int(row['Insulin'])<25) and (int(row['Pregnancies'])<6)):
            if(int(row['Age'])<30):
                return 1
            else :
                return 0
        else:
            return 0

    else:
        return 0

def calculate_Hypertension(row):
    if (row['Outcome']) == '1':
        if((int(row['Insulin'])<25) and (int(row['Pregnancies'])<6)):
            return 0
        else:
            if ((int(row['BloodPressure'])>80) and (int(row['BloodPressure'])<90)) :
                return 1
            elif ((int(row['BloodPressure'])>90) and (int(row['BloodPressure'])<119)):
                return 2
            elif ((int(row['BloodPressure'])>119)):
                return 3
            return 0

    else:
        return 0

thedata['DKAprone']= thedata.apply(calculate_dkaprone,axis=1)
thedata['Hypertension']= thedata.apply(calculate_Hypertension,axis=1)


thedata.to_csv('diabetes.csv', index= False)

In [55]:
thedata

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Type,DKAprone,Hypertension
0,6,148,72,35,0,33.6,0.627,50,1,0,0,0
1,1,85,66,29,0,26.6,0.351,31,0,0,0,0
2,8,183,64,0,0,23.3,0.672,32,1,0,0,0
3,1,89,66,23,94,28.1,0.167,21,0,0,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0,0,0
764,2,122,70,27,0,36.8,0.340,27,0,0,0,0
765,5,121,72,23,112,26.2,0.245,30,0,0,0,0
766,1,126,60,0,0,30.1,0.349,47,1,0,0,0
767,1,93,70,31,0,30.4,0.315,23,0,0,0,0

In [56]:
thedata.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Type,DKAprone,Hypertension
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.0,768.0,768.0
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958,0.0,0.0,0.0
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951,0.0,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000,0.0,0.0,0.0
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000,0.0,0.0,0.0
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000,0.0,0.0,0.0
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000,0.0,0.0,0.0
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000,0.0,0.0,0.0

The above data shows that majority of patients in the dataset are not prone to Diabetic Ketoacidosis or Hypertension.

On observing

- Hypertension: the min and max values are 0 and 2 respectively. This indicates that no patient has stage 3 hypertension. The mean value suggests that majority of the outcomes are towards 0 thus, supporting our conclusion.

- DKAprone: the min and max values are 0 and 1 respectively. The mean value suggests that the majority of outcomes are leaning toward 0, suggesting that majority of patients are not prone to Diabetic Ketoacidosis.